language: ruby
rvm:
  - 1.8.7
#  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
#  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
#  - rbx-19mode
env:
  - POSTGIS=1.5
  - POSTGIS=2.0
gemfile:
  - travis/ar30.gemfile
  - travis/ar31.gemfile
  - travis/ar32.gemfile
  - travis/ar40.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: travis/ar40.gemfile
      env: POSTGIS=1.5
    - rvm: 1.8.7
      gemfile: travis/ar40.gemfile
      env: POSTGIS=2.0
    - rvm: jruby-18mode
      gemfile: travis/ar40.gemfile
      env: POSTGIS=1.5
    - rvm: jruby-18mode
      gemfile: travis/ar40.gemfile
      env: POSTGIS=2.0
    - rvm: rbx-18mode
      gemfile: travis/ar40.gemfile
      env: POSTGIS=1.5
    - rvm: rbx-18mode
      gemfile: travis/ar40.gemfile
      env: POSTGIS=2.0
# TEMP: jdbc adapters don't seem to work with Rails 4 yet, as of 2013-02-27
    - rvm: jruby-19mode
      gemfile: travis/ar40.gemfile
      env: POSTGIS=1.5
    - rvm: jruby-19mode
      gemfile: travis/ar40.gemfile
      env: POSTGIS=2.0
# END TEMP
before_install: ./travis/before_install.sh
before_script: ./travis/before_script.sh
script: bundle exec rake test
