language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.0.0
  - 1.9.3
  - rbx-2

gemfile:
  - Gemfile
matrix:
  allow_failures:
    - rvm: rbx-2
before_install: ./travis/before_install.sh
script: bundle exec rake test

addons:
  postgresql: "9.3"