language: ruby
rvm:
  - 2.2.2
  - jruby
  - rbx-2
gemfile:
  - gemfiles/ar50.gemfile
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
addons:
  postgresql: "9.3"
before_script:
  - psql -U postgres -c "create database postgis_adapter_test"
  - psql -U postgres -d postgis_adapter_test -c "create extension postgis"
script: bundle exec rake test
